name: reels
description: "A Flutter package for displaying short videos like Instagram Reels, TikTok, or YouTube Shorts."
version: 1.0.0
homepage: https://github.com/risfat/reels
repository: https://github.com/risfat/reels

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.10.0
  http: ^1.4.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
